# Source the RubyGems repository
source "https://rubygems.org"

# Specify the version of Rails to use
# The "~> 8.0.1" syntax specifies that any version of Rails from 8.0.1 to less than 9.0.0 is acceptable
gem "rails", "~> 8.0.1"

# The modern asset pipeline for Rails
# Propshaft is a replacement for the traditional Sprockets asset pipeline
gem "propshaft"

# Use the Puma web server
# Puma is a fast and efficient web server for Ruby and Rack applications
gem "puma", ">= 5.0"

# Use JavaScript with ESM import maps
# Importmap-rails provides support for ESM import maps in Rails applications
gem "importmap-rails"

# Hotwire's SPA-like page accelerator
# Turbo-rails provides support for Turbo, a library for building fast and efficient web applications
gem "turbo-rails"

# Hotwire's modest JavaScript framework
# Stimulus-rails provides support for Stimulus, a JavaScript framework for building reusable UI components
gem "stimulus-rails"

# Build JSON APIs with ease
# Jbuilder is a gem for building JSON APIs in Rails applications
gem "jbuilder"

# Twilio Ruby library
# This gem provides support for interacting with the Twilio API
gem 'twilio-ruby'

# Mongoid ORM for MongoDB
# This gem provides support for interacting with MongoDB databases in Rails applications
gem 'mongoid'

# Rack CORS middleware
# This gem provides support for handling CORS requests in Rails applications
gem 'rack-cors'

# Timezone data for Windows and JRuby
# This gem provides timezone data for Windows and JRuby platforms
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Bootsnap caching
# This gem provides support for caching and speeding up Rails applications
gem "bootsnap", require: false

# Kamal deployment
# This gem provides support for deploying Rails applications as Docker containers
gem "kamal", require: false

# Thruster caching and compression
# This gem provides support for caching, compression, and X-Sendfile acceleration in Puma
gem "thruster", require: false

# Development and test group
group :development, :test do
  # Debugging tools
  # This gem provides support for debugging Rails applications
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Dotenv configuration
  # This gem provides support for loading environment variables from a .env file
  gem 'dotenv-rails'

  # Brakeman security scanner
  # This gem provides support for scanning Rails applications for security vulnerabilities
  gem "brakeman", require: false

  # Rubocop code style checker
  # This gem provides support for checking the code style of Rails applications
  gem "rubocop-rails-omakase", require: false
end

# Development group
group :development do
  # Web console
  # This gem provides support for displaying a web console in Rails applications
  gem "web-console"
end

# Test group
group :test do
  # Capybara testing
  # This gem provides support for testing Rails applications with Capybara
  gem "capybara"

  # Selenium WebDriver
  # This gem provides support for testing Rails applications with Selenium WebDriver
  gem "selenium-webdriver"
end
