twilio:
  account_sid: your_account_sid
  auth_token: your_auth_token
  from_phone_number: your_from_phone_number


# smtp:
#   user_name: my-smtp-user
#   password: my-smtp-password
#
# aws:
#   access_key_id: 123
#   secret_access_key: 345

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: 277ad792b3ba316194217a27fb0b8b6a2dc9f592f01bf8408ab5b9740099fe98238ad8c628efefc6653564ff4118d95ce1fe634aba2c68e9d622ab4c6c66feb5